stages:
  - build
  - deploy

build-code-job:
  stage: build
  tags:
    - docker
  image: node:18-buster
  script:
    - npm i minify -g
    - minify server.js > server.min.js
    - minify app.js > app.min.js
    - minify public/app.js > public/app.min.js
    - minify public/globe.js > public/globe.min.js
    - minify public/particles.js > public/particles.min.js
    - minify public/planetaryjs.js > public/planetaryjs.min.js

deploy-code-job:
  stage: deploy
  image: node:18-buster
  variables:
    GITHUB_URL: git@github.com:KimvanSt/express-hello-world.git
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - ssh-add <(echo "$PRIVATE_SSH_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  script:
    - git checkout main
    - git merge feature
    - git remote add origin $GITHUB_URL
    - git add . && commit -m 'automatic deployment from gitlab' && git push -u origin/main
